/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package monasheasts;

import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import monasheasts.entities.FoodDetailsEntity;
import monasheasts.entities.FoodEntity;

/**
 *
 * @author ojas
 */
public class UserCart extends javax.swing.JFrame {

    List<FoodEntity> foodList;
    List<FoodDetailsEntity> foodDetailsList;
    int selectFoodItemId;
    DefaultListModel cartModel = new DefaultListModel();

    /**
     * Creates new form UserCart
     */
    public UserCart() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        userCartTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setText("User Cart");

        jButton3.setText("Proceed to Payment");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jButton4.setText("Increase Item");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Decrease Item");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        userCartTotal.setText("Total");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userCartTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jButton4)
                                .addGap(18, 18, 18)
                                .addComponent(jButton5))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4)
                            .addComponent(jButton5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(userCartTotal)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        UserCart uCart = new UserCart();
        UserPayment uPayment = new UserPayment();
        uCart.setVisible(false);
        uPayment.setVisible(true);
        dispose();

    }//GEN-LAST:event_jButton3ActionPerformed

    private void displayPrice(){
        int totalItemCost = 0 ;
        for(FoodDetailsEntity foodDetail:foodDetailsList){
            totalItemCost += foodDetail.getPrice();
        }
        userCartTotal.setText("Total: " + totalItemCost);
    }
    
    
    public void loadCart() {

        for (FoodEntity foodEntity : foodList) {
            cartModel.addElement("Food Name: " + foodEntity.getFoodName() + ", Price: " + foodEntity.getFoodPrice());
        }
        jList1.setModel(cartModel);
    }

    private void increaseFoodDetails() {
        selectFoodItemId = jList1.getSelectedIndex();
        int selectedItemQuantity = foodDetailsList.get(selectFoodItemId).getQuantity();
        selectedItemQuantity += 1;
        double foodItemPrice = foodList.get(selectFoodItemId).getFoodPrice();
        foodDetailsList.get(selectFoodItemId).setQuantity(selectedItemQuantity);
        foodDetailsList.get(selectFoodItemId).setPrice(foodItemPrice * selectedItemQuantity);
        cartModel.setElementAt("Food Name: " + foodList.get(selectFoodItemId).getFoodName() + ", Price: " + foodDetailsList.get(selectFoodItemId).getPrice() + " Quantity: " + foodDetailsList.get(selectFoodItemId).getQuantity(), selectFoodItemId);
        System.out.println("Selected item Name: " + foodList.get(selectFoodItemId).getFoodName() + " Quantity: " + foodDetailsList.get(selectFoodItemId).getQuantity());
        displayPrice();
    }

    private void decreaseFoodDetails() {
        selectFoodItemId = jList1.getSelectedIndex();
        int selectedItemQuantity = foodDetailsList.get(selectFoodItemId).getQuantity();
        selectedItemQuantity -= 1;
        double foodItemPrice = foodList.get(selectFoodItemId).getFoodPrice();
        double currentItemPrice = foodDetailsList.get(selectFoodItemId).getPrice();
        if (selectedItemQuantity <= 0) {
            cartModel.removeElementAt(selectFoodItemId);
        } else {
            foodDetailsList.get(selectFoodItemId).setQuantity(selectedItemQuantity);
            foodDetailsList.get(selectFoodItemId).setPrice(currentItemPrice - foodItemPrice);
            cartModel.setElementAt("Food Name: " + foodList.get(selectFoodItemId).getFoodName() + ", Price: " + foodDetailsList.get(selectFoodItemId).getPrice() + " Quantity: " + foodDetailsList.get(selectFoodItemId).getQuantity(), selectFoodItemId);
        }
        displayPrice();
    }

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        increaseFoodDetails();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        decreaseFoodDetails();
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserCart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserCart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserCart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserCart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserCart().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel userCartTotal;
    // End of variables declaration//GEN-END:variables
}
